# Generated by Django 3.0.4 on 2020-03-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodypartexcercise',
            name='fitness_level',
            field=models.CharField(choices=[('Beginer', 'Beginer'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Beginer', max_length=20),
        ),
        migrations.AddField(
            model_name='bodypartexcercise',
            name='fitness_plan',
            field=models.CharField(choices=[('Weight Gain', 'Weight Gain'), ('Fat lose', 'Fat lose')], default='Fat lose', max_length=20),
        ),
        migrations.AddField(
            model_name='bodypartexcercise',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='fitness_plan',
            field=models.CharField(choices=[('Weight Gain', 'Weight Gain'), ('Fat lose', 'Fat lose')], default='Fat lose', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
        ),
    ]
