# Generated by Django 3.0.4 on 2020-03-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20200328_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='image',
            field=models.ImageField(null=True, upload_to='excercises'),
        ),
        migrations.AlterField(
            model_name='bodypartexcercise',
            name='fitness_plan',
            field=models.CharField(choices=[('Gain', 'Gain'), ('lose', 'lose')], default='lose', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='fitness_plan',
            field=models.CharField(choices=[('Gain', 'Gain'), ('lose', 'lose')], default='lose', max_length=20),
        ),
    ]
