# Generated by Django 3.0.4 on 2020-03-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20200329_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypartexcercise',
            name='fitness_level',
            field=models.CharField(choices=[('beginer', 'beginer'), ('intermediate', 'intermediate'), ('advance', 'advance')], default='beginer', max_length=20),
        ),
        migrations.AlterField(
            model_name='bodypartexcercise',
            name='fitness_plan',
            field=models.CharField(choices=[('gain', 'gain'), ('lose', 'lose')], default='lose', max_length=20),
        ),
        migrations.AlterField(
            model_name='bodypartexcercise',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='fitness_plan',
            field=models.CharField(choices=[('gain', 'gain'), ('lose', 'lose')], default='lose', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20),
        ),
    ]
