# Generated by Django 3.0.4 on 2020-03-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20200329_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodypartexcercise',
            name='reps',
            field=models.IntegerField(default=0),
        ),
    ]
